# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34597382569818ba493b442d5882b28140ca1b3dc762bec11269e6aa9ca1fb8ca470391d9fd06752ae203e01624f82008ed31f02fb76bd1ae2176077c5733aa4

test:
  secret_key_base: f4c94aaff5ba9347c4a2aca7e221421af2d1566dc78d4a46e2afc4a53c3780e9d368798582a31b66d82511708011621e56d019fa8efc2b19f58dc928907b3974

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
